# Generated by Django 2.2.6 on 2021-04-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
