# Generated by Django 2.2.6 on 2021-04-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='Новый пост', help_text='Введите название поста', verbose_name='Название поста'),
        ),
    ]
